.TH "src/display Directory Reference" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/display Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcurses\fP"
.br
.ti -1c
.RI "directory \fBsdl\fP"
.br
.ti -1c
.RI "directory \fBsfml\fP"
.br
.in -1c
