.TH "games/nibbler/include/misc Directory Reference" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
games/nibbler/include/misc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCell\&.hpp\fP"
.br
.ti -1c
.RI "file \fBDirection\&.hpp\fP"
.br
.in -1c
