.TH "include/exceptions Directory Reference" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/exceptions Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDLopenFailure\&.hpp\fP"
.br
.ti -1c
.RI "file \fBFileNotCompatible\&.hpp\fP"
.br
.ti -1c
.RI "file \fBLibNotAvailable\&.hpp\fP"
.br
.in -1c
