.TH "cmake-build-debug Directory Reference" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmake-build-debug Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBCMakeFiles\fP"
.br
.ti -1c
.RI "directory \fBgames\fP"
.br
.ti -1c
.RI "directory \fBPacman\fP"
.br
.in -1c
