.TH "arcade::resources::Color" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arcade::resources::Color \- The color class allows you to interact with colors\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Color\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColor\fP (std::uint8_t red=255, std::uint8_t green=255, std::uint8_t blue=255, std::uint8_t opacity=255)"
.br
.ti -1c
.RI "void \fBsetRed\fP (std::uint8_t val)"
.br
.ti -1c
.RI "void \fBsetGreen\fP (std::uint8_t val)"
.br
.ti -1c
.RI "void \fBsetBlue\fP (std::uint8_t val)"
.br
.ti -1c
.RI "void \fBsetOpacity\fP (std::uint8_t val)"
.br
.ti -1c
.RI "std::uint8_t \fBgetRed\fP () const"
.br
.ti -1c
.RI "std::uint8_t \fBgetGreen\fP () const"
.br
.ti -1c
.RI "std::uint8_t \fBgetBlue\fP () const"
.br
.ti -1c
.RI "std::uint8_t \fBgetOpacity\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
The color class allows you to interact with colors\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "arcade::resources::Color::Color (std::uint8_t red = \fC255\fP, std::uint8_t green = \fC255\fP, std::uint8_t blue = \fC255\fP, std::uint8_t opacity = \fC255\fP)"

.SH "Member Function Documentation"
.PP 
.SS "std::uint8_t arcade::resources::Color::getBlue () const\fC [inline]\fP"
blue value getter 
.PP
\fBReturns\fP
.RS 4
This method return the blue value of the color 
.RE
.PP

.SS "std::uint8_t arcade::resources::Color::getGreen () const\fC [inline]\fP"
green value getter 
.PP
\fBReturns\fP
.RS 4
This method return the green value of the color 
.RE
.PP

.SS "std::uint8_t arcade::resources::Color::getOpacity () const\fC [inline]\fP"
opacity value getter 
.PP
\fBReturns\fP
.RS 4
This method return the opacity value of the color 
.RE
.PP

.SS "std::uint8_t arcade::resources::Color::getRed () const\fC [inline]\fP"
red value getter 
.PP
\fBReturns\fP
.RS 4
This method return the red value of the color 
.RE
.PP

.SS "void arcade::resources::Color::setBlue (std::uint8_t val)\fC [inline]\fP"
blue value setter 
.PP
\fBParameters\fP
.RS 4
\fIval\fP The val parameter refers to new value 
.RE
.PP

.SS "void arcade::resources::Color::setGreen (std::uint8_t val)\fC [inline]\fP"
green value setter 
.PP
\fBParameters\fP
.RS 4
\fIval\fP The val parameter refers to new value 
.RE
.PP

.SS "void arcade::resources::Color::setOpacity (std::uint8_t val)\fC [inline]\fP"
opacity value setter 
.PP
\fBParameters\fP
.RS 4
\fIval\fP The val parameter refers to new value 
.RE
.PP

.SS "void arcade::resources::Color::setRed (std::uint8_t val)\fC [inline]\fP"
red value setter 
.PP
\fBParameters\fP
.RS 4
\fIval\fP The val parameter refers to new value 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
