.TH "arcade::exceptions" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arcade::exceptions
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDLopenFailure\fP"
.br
.RI "The \fBFileNotCompatible\fP class is an exception that will be thrown if dlopen fails\&. "
.ti -1c
.RI "class \fBFileNotCompatible\fP"
.br
.RI "The \fBFileNotCompatible\fP class is an exception that will be thrown if the user give an non-implemented file\&. "
.ti -1c
.RI "class \fBLibNotAvailable\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
