.TH "arcade" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arcade
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBexceptions\fP"
.br
.ti -1c
.RI " \fBprotocols\fP"
.br
.ti -1c
.RI " \fBresources\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCoords\fP"
.br
.RI "This structure can be used to represent 2D coordinates\&. "
.ti -1c
.RI "struct \fBRect\fP"
.br
.RI "this struct can be used to represent a rectangle "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBTime\fP = double"
.br
.RI "The Time type refers to a double that will be used to calculate an element position relative to time\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBInterfaceType\fP { \fBIGame\fP, \fBIGraphical\fP }"
.br
.RI "The InterfaceType enum contains all interfaces name (will be used with dlsym to know which interface we are using) "
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "\fBarcade::Time\fP"

.PP
The Time type refers to a double that will be used to calculate an element position relative to time\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBarcade::InterfaceType\fP"

.PP
The InterfaceType enum contains all interfaces name (will be used with dlsym to know which interface we are using) 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIIGame \fP\fP
.TP
\fB\fIIGraphical \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
