.TH "arcade::resources" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arcade::resources
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBColor\fP"
.br
.RI "The color class allows you to interact with colors\&. "
.ti -1c
.RI "struct \fBSprite\fP"
.br
.RI "the \fBSprite\fP structure can be used to represent a sprite on the screen "
.ti -1c
.RI "struct \fBText\fP"
.br
.RI "the \fBText\fP struct can be used to represent a text in all modes (sfml, sdl, ncurses, opengl, etc\&.\&.\&.) "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBColorType\fP { \fBBACKGROUND\fP, \fBFOREGROUND\fP }"
.br
.RI "The ColorType enum allow you to chose the color type you wanna use\&. "
.ti -1c
.RI "enum \fBKeys\fP { \fBUnknown\fP = -1, \fBA\fP = 0, \fBB\fP, \fBC\fP, \fBD\fP, \fBE\fP, \fBF\fP, \fBG\fP, \fBH\fP, \fBI\fP, \fBJ\fP, \fBK\fP, \fBL\fP, \fBM\fP, \fBN\fP, \fBO\fP, \fBP\fP, \fBQ\fP, \fBR\fP, \fBS\fP, \fBT\fP, \fBU\fP, \fBV\fP, \fBW\fP, \fBX\fP, \fBY\fP, \fBZ\fP, \fBEscape\fP, \fBSpace\fP, \fBEnter\fP, \fBLeft\fP, \fBRight\fP, \fBUp\fP, \fBDown\fP, \fBClose\fP, \fBReturn\fP }"
.br
.RI "This enum contains all the key codes available for arcade\&. "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBarcade::resources::ColorType\fP"

.PP
The ColorType enum allow you to chose the color type you wanna use\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIBACKGROUND \fP\fP
.TP
\fB\fIFOREGROUND \fP\fP
.SS "enum \fBarcade::resources::Keys\fP"

.PP
This enum contains all the key codes available for arcade\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUnknown \fP\fP
.TP
\fB\fIA \fP\fP
.TP
\fB\fIB \fP\fP
.TP
\fB\fIC \fP\fP
.TP
\fB\fID \fP\fP
.TP
\fB\fIE \fP\fP
.TP
\fB\fIF \fP\fP
.TP
\fB\fIG \fP\fP
.TP
\fB\fIH \fP\fP
.TP
\fB\fII \fP\fP
.TP
\fB\fIJ \fP\fP
.TP
\fB\fIK \fP\fP
.TP
\fB\fIL \fP\fP
.TP
\fB\fIM \fP\fP
.TP
\fB\fIN \fP\fP
.TP
\fB\fIO \fP\fP
.TP
\fB\fIP \fP\fP
.TP
\fB\fIQ \fP\fP
.TP
\fB\fIR \fP\fP
.TP
\fB\fIS \fP\fP
.TP
\fB\fIT \fP\fP
.TP
\fB\fIU \fP\fP
.TP
\fB\fIV \fP\fP
.TP
\fB\fIW \fP\fP
.TP
\fB\fIX \fP\fP
.TP
\fB\fIY \fP\fP
.TP
\fB\fIZ \fP\fP
.TP
\fB\fIEscape \fP\fP
.TP
\fB\fISpace \fP\fP
.TP
\fB\fIEnter \fP\fP
.TP
\fB\fILeft \fP\fP
.TP
\fB\fIRight \fP\fP
.TP
\fB\fIUp \fP\fP
.TP
\fB\fIDown \fP\fP
.TP
\fB\fIClose \fP\fP
.TP
\fB\fIReturn \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
