.TH "arcade::exceptions::FileNotCompatible" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arcade::exceptions::FileNotCompatible \- The \fBFileNotCompatible\fP class is an exception that will be thrown if the user give an non-implemented file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FileNotCompatible\&.hpp>\fP
.PP
Inherits std::exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileNotCompatible\fP (const char *msg)"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const noexcept override"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBFileNotCompatible\fP class is an exception that will be thrown if the user give an non-implemented file\&. 

The \fBLibNotAvailable\fP class is an exception that will be thrown if the user try to switch to a library that is not available\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "arcade::exceptions::FileNotCompatible::FileNotCompatible (const char * msg)\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const char* arcade::exceptions::FileNotCompatible::what () const\fC [inline]\fP, \fC [override]\fP, \fC [noexcept]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
