.TH "arcade::Rect< T >" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arcade::Rect< T > \- this struct can be used to represent a rectangle  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Common\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBx\fP"
.br
.ti -1c
.RI "T \fBy\fP"
.br
.ti -1c
.RI "T \fBw\fP"
.br
.ti -1c
.RI "T \fBh\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct arcade::Rect< T >"
this struct can be used to represent a rectangle 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Type T refers to storage type (double, long, int, etc) 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "template<typename T > \fBarcade::Rect\fP< T >::h"
The h var refers to height 
.SS "template<typename T > \fBarcade::Rect\fP< T >::w"
The w var refers to width 
.SS "template<typename T > \fBarcade::Rect\fP< T >::x"
The x var refers to x coordinate 
.SS "template<typename T > \fBarcade::Rect\fP< T >::y"
The y var refers to y coordinate 

.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
