.TH "arcade::protocols::DisplayProtocol" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arcade::protocols::DisplayProtocol \- The \fBDisplayProtocol\fP contains all the information to show data on screen\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DisplayProtocol\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::queue< \fBarcade::resources::Sprite\fP > \fBsprites\fP"
.br
.ti -1c
.RI "std::queue< \fBarcade::resources::Text\fP > \fBtexts\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBDisplayProtocol\fP contains all the information to show data on screen\&. 
.SH "Member Data Documentation"
.PP 
.SS "arcade::protocols::DisplayProtocol::sprites"
Member 'sprites' refers to a queue of sprites 
.SS "arcade::protocols::DisplayProtocol::texts"
Member 'texts' refers to a queue of texts 

.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
