.TH "arcade::protocols" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arcade::protocols
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDisplayProtocol\fP"
.br
.RI "The \fBDisplayProtocol\fP contains all the information to show data on screen\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
