.TH "games/nibbler/include/misc/Cell.hpp" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
games/nibbler/include/misc/Cell.hpp
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgames\fP"
.br
.ti -1c
.RI " \fBgames::misc\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBgames::misc::NibblerCell\fP { \fBgames::misc::VOID\fP, \fBgames::misc::FOOD\fP, \fBgames::misc::WALL\fP, \fBgames::misc::HEAD\fP, \fBgames::misc::BODY\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
