.TH "games/solarfox/CMakeLists.txt" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
games/solarfox/CMakeLists.txt
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBadd_library\fP (solarfox SHARED main\&.cpp src/SolarFox\&.cpp) set_target_properties(solarfox PROPERTIES PREFIX 'arcade_' LIBRARY_OUTPUT_DIRECTORY '$"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "add_library (solarfox SHARED main\&.cpp src/SolarFox\&. cpp)"

.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
