.TH "cmake-build-debug/CMakeCache.txt" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmake-build-debug/CMakeCache.txt
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "B_OOP_400_PAR_4_1_arcade_mihailo_pavlovic_BINARY_DIR \fB__pad0__\fP"
.br
.ti -1c
.RI "\fBD_XOPEN_SOURCE\fP"
.br
.ti -1c
.RI "\fBO1\fP"
.br
.ti -1c
.RI "sort \fBcommon\fP"
.br
.ti -1c
.RI "sort as \fBneeded\fP"
.br
.ti -1c
.RI "sort as \fBz\fP"
.br
.ti -1c
.RI "sort as \fBrelro\fP"
.br
.ti -1c
.RI "sort as \fBnow\fP"
.br
.ti -1c
.RI "lncursesw \fBNCURSES_LDFLAGS_OTHER\fP"
.br
.ti -1c
.RI "lncursesw sort as \fBnow\fP \fBNCURSES_LIBDIR\fP"
.br
.ti -1c
.RI "lncursesw \fBNCURSES_STATIC_LDFLAGS_OTHER\fP"
.br
.ti -1c
.RI "lncursesw sort as \fBnow\fP \fBNCURSES_STATIC_LIBDIR\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "B_OOP_400_PAR_4_1_arcade_mihailo_pavlovic_BINARY_DIR __pad0__"

.SS "lncursesw sort common"

.SS "D_XOPEN_SOURCE"
\fBInitial value:\fP
.PP
.nf
=600
NCURSES_CFLAGS_I:INTERNAL=
NCURSES_CFLAGS_OTHER:INTERNAL=-D_DEFAULT_SOURCE
.fi
.SS "lncursesw NCURSES_LDFLAGS_OTHER"

.SS "lncursesw sort as \fBnow\fP NCURSES_LIBDIR"

.SS "lncursesw NCURSES_STATIC_LDFLAGS_OTHER"

.SS "lncursesw sort as \fBnow\fP NCURSES_STATIC_LIBDIR"

.SS "lncursesw sort as needed"

.SS "sort as now"

.SS "lncursesw O1"

.SS "lncursesw sort as relro"

.SS "lncursesw sort as z"

.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
