.TH "include/resources/Color.hpp" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/resources/Color.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBarcade::resources::Color\fP"
.br
.RI "The color class allows you to interact with colors\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBResources\fP"
.br
.RI "The \fBResources\fP namespace contains all arcade resources\&. "
.ti -1c
.RI " \fBarcade\fP"
.br
.ti -1c
.RI " \fBarcade::resources\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBarcade::resources::ColorType\fP { \fBarcade::resources::BACKGROUND\fP, \fBarcade::resources::FOREGROUND\fP }"
.br
.RI "The ColorType enum allow you to chose the color type you wanna use\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
