.TH "core/src/Core.cpp" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/src/Core.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <functional>\fP
.br
\fC#include <exceptions/LibNotAvailable\&.hpp>\fP
.br
\fC#include <filesystem>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include '\&.\&./include/Greeter\&.hpp'\fP
.br
\fC#include '\&.\&./include/Core\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
