.TH "include/display/Curses.hpp" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/display/Curses.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <chrono>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <interfaces/IGraphical\&.hpp>\fP
.br
\fC#include <resources/KeyTranslation\&.hpp>\fP
.br
\fC#include <protocols/DisplayProtocol\&.hpp>\fP
.br
\fC#include <misc/CursesWrapper\&.hpp>\fP
.br
\fC#include <Common\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdisplay::Curses\fP"
.br
.RI "The \fBCurses\fP class is the IGraphical implementation for ncurses lib\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBGames\fP"
.br
.RI "The namespace \fBGames\fP contains various classes that will be used to make the Game system work\&. "
.ti -1c
.RI " \fBdisplay\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
