.TH "src/display/curses/Curses.cpp" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/display/curses/Curses.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <thread>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <display/Curses\&.hpp>\fP
.br
\fC#include <misc/CursesWrapper\&.hpp>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
