.TH "games/nibbler/include/misc/Direction.hpp" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
games/nibbler/include/misc/Direction.hpp
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgames\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBgames::Direction\fP { \fBgames::TOP\fP, \fBgames::BOTTOM\fP, \fBgames::LEFT\fP, \fBgames::RIGHT\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
