.TH "include/protocols/DisplayProtocol.hpp" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/protocols/DisplayProtocol.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <queue>\fP
.br
\fC#include <resources/Sprite\&.hpp>\fP
.br
\fC#include <resources/Text\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBarcade::protocols::DisplayProtocol\fP"
.br
.RI "The \fBDisplayProtocol\fP contains all the information to show data on screen\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBProtocols\fP"
.br
.RI "The namespace \fBProtocols\fP contains the structures that will be used to communicate between the GFX and \fBCore\fP parts\&. It contains protocols like GameProtocol, DisplayProtocol, etc\&. "
.ti -1c
.RI " \fBarcade\fP"
.br
.ti -1c
.RI " \fBarcade::protocols\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
