.TH "display" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
display
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCurses\fP"
.br
.RI "The \fBCurses\fP class is the IGraphical implementation for ncurses lib\&. "
.ti -1c
.RI "class \fBSdl\fP"
.br
.RI "The \fBSdl\fP class is the IGraphical implementation for SDL2 lib\&. "
.ti -1c
.RI "class \fBSfml\fP"
.br
.RI "The \fBCurses\fP class is the IGraphical implementation for \fBSfml\fP lib\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
