.TH "include/misc/DLWrapper.hpp" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/misc/DLWrapper.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include <link\&.h>\fP
.br
\fC#include <queue>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <exceptions/FileNotCompatible\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmisc::DLWrapper\fP"
.br
.RI "the \fBDLWrapper\fP class is an encapsulation of the libdl "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMisc\fP"
.br
.RI "The \fBMisc\fP namespace contains data that doesnt belong to any particular category\&. "
.ti -1c
.RI " \fBmisc\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
