.TH "src/misc/DLWrapper.cpp" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/misc/DLWrapper.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <misc/DLWrapper\&.hpp>\fP
.br
\fC#include <exceptions/DLopenFailure\&.hpp>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
