.TH "Exceptions" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Exceptions \- The \fBExceptions\fP namespace contains various exceptions that are needed to make the arcade work\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
The \fBExceptions\fP namespace contains various exceptions that are needed to make the arcade work\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
