.TH "include/exceptions/FileNotCompatible.hpp" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/exceptions/FileNotCompatible.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string_view>\fP
.br
\fC#include <exception>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBarcade::exceptions::FileNotCompatible\fP"
.br
.RI "The \fBFileNotCompatible\fP class is an exception that will be thrown if the user give an non-implemented file\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBExceptions\fP"
.br
.RI "The \fBExceptions\fP namespace contains various exceptions that are needed to make the arcade work\&. "
.ti -1c
.RI " \fBarcade\fP"
.br
.ti -1c
.RI " \fBarcade::exceptions\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
