.TH "games::misc" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
games::misc
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBNibblerCell\fP { \fBVOID\fP, \fBFOOD\fP, \fBWALL\fP, \fBHEAD\fP, \fBBODY\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBgames::misc::NibblerCell\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIVOID \fP\fP
.TP
\fB\fIFOOD \fP\fP
.TP
\fB\fIWALL \fP\fP
.TP
\fB\fIHEAD \fP\fP
.TP
\fB\fIBODY \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
