.TH "core/src/Greeter.cpp" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/src/Greeter.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include '\&.\&./include/Greeter\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
