.TH "core/include/Greeter.hpp" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/include/Greeter.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <interfaces/IGame\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcore::Greeter\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBCore\fP"
.br
.RI "The namespace \fBCore\fP contains various classes that will be used to make the \fBCore\fP work\&. "
.ti -1c
.RI " \fBcore\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
