.TH "include/interfaces/IGame.hpp" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/interfaces/IGame.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <queue>\fP
.br
\fC#include <resources/Keys\&.hpp>\fP
.br
\fC#include <Common\&.hpp>\fP
.br
\fC#include <protocols/DisplayProtocol\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBinterfaces::IGame\fP"
.br
.RI "the \fBIGame\fP intgerface defines game libraries behavior "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBInterfaces\fP"
.br
.RI "The namespace Interface contains all program interfaces\&. It contains interfaces like IGame, IGraphical, etc\&. "
.ti -1c
.RI " \fBinterfaces\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
