.TH "interfaces" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
interfaces
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBIGame\fP"
.br
.RI "the \fBIGame\fP intgerface defines game libraries behavior "
.ti -1c
.RI "interface \fBIGraphical\fP"
.br
.RI "the \fBIGraphical\fP interface defines graphical libraries behavior "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
