.TH "include/exceptions/LibNotAvailable.hpp" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/exceptions/LibNotAvailable.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <utility>\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBarcade::exceptions::LibNotAvailable\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBExceptions\fP"
.br
.RI "The \fBExceptions\fP namespace contains various exceptions that are needed to make the arcade work\&. "
.ti -1c
.RI " \fBarcade\fP"
.br
.ti -1c
.RI " \fBarcade::exceptions\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
