.TH "cmake-build-debug/Pacman/CMakeFiles/arcade_pacman.dir/link.txt" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmake-build-debug/Pacman/CMakeFiles/arcade_pacman.dir/link.txt
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "usr bin c fPIC Wall Wextra g shared \fBWl\fP"
.br
.ti -1c
.RI "usr bin c fPIC Wall Wextra g shared \fBsoname\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "usr bin c fPIC Wall Wextra g shared soname"

.SS "usr bin c fPIC Wall Wextra g shared Wl"

.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
