.TH "src/display/sfml/main.cpp" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/display/sfml/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <display/Sfml\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBinterfaces::IGraphical\fP * \fBentryPoint\fP ()"
.br
.ti -1c
.RI "\fBarcade::InterfaceType\fP \fBgetType\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBinterfaces::IGraphical\fP* entryPoint ()"

.SS "\fBarcade::InterfaceType\fP getType ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
