.TH "misc" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
misc
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCursesWrapper\fP"
.br
.RI "the \fBCursesWrapper\fP class is an encapsulation of the lib ncurses "
.ti -1c
.RI "class \fBDLWrapper\fP"
.br
.RI "the \fBDLWrapper\fP class is an encapsulation of the libdl "
.ti -1c
.RI "class \fBSdlWrapper\fP"
.br
.RI "the \fBSdlWrapper\fP class is an encapsulation of the lib ncurses "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
