.TH "games/nibbler/src/Nibbler.cpp" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
games/nibbler/src/Nibbler.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include '\&.\&./include/Nibbler\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
