.TH "games/nibbler/include/Nibbler.hpp" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
games/nibbler/include/Nibbler.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <interfaces/IGame\&.hpp>\fP
.br
\fC#include <array>\fP
.br
\fC#include 'misc/Cell\&.hpp'\fP
.br
\fC#include 'Snake\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgames::Nibbler\fP"
.br
.RI "The \fBNibbler\fP class is the IGame implementation for \fBNibbler\fP game\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBGames\fP"
.br
.RI "The namespace \fBGames\fP contains various classes that will be used to make the Game system work\&. "
.ti -1c
.RI " \fBgames\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
