.TH "Protocols" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Protocols \- The namespace \fBProtocols\fP contains the structures that will be used to communicate between the GFX and \fBCore\fP parts\&. It contains protocols like GameProtocol, DisplayProtocol, etc\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
The namespace \fBProtocols\fP contains the structures that will be used to communicate between the GFX and \fBCore\fP parts\&. It contains protocols like GameProtocol, DisplayProtocol, etc\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
