.TH "Resources" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Resources \- The \fBResources\fP namespace contains all arcade resources\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
The \fBResources\fP namespace contains all arcade resources\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
