.TH "src/display/sdl/Sdl.cpp" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/display/sdl/Sdl.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <thread>\fP
.br
\fC#include <display/Sdl\&.hpp>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
