.TH "games/nibbler/include/Snake.hpp" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
games/nibbler/include/Snake.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <Common\&.hpp>\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'misc/Direction\&.hpp'\fP
.br
\fC#include 'misc/Cell\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgames::Snake\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgames\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
