.TH "include/resources/Sprite.hpp" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/resources/Sprite.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string_view>\fP
.br
\fC#include <Common\&.hpp>\fP
.br
\fC#include 'Color\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBarcade::resources::Sprite\fP"
.br
.RI "the \fBSprite\fP structure can be used to represent a sprite on the screen "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBResources\fP"
.br
.RI "The \fBResources\fP namespace contains all arcade resources\&. "
.ti -1c
.RI " \fBarcade\fP"
.br
.ti -1c
.RI " \fBarcade::resources\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
