.TH "include/resources/Text.hpp" 3 "Sun Apr 11 2021" "arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/resources/Text.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string_view>\fP
.br
\fC#include <Common\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBarcade::resources::Text\fP"
.br
.RI "the \fBText\fP struct can be used to represent a text in all modes (sfml, sdl, ncurses, opengl, etc\&.\&.\&.) "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBResources\fP"
.br
.RI "The \fBResources\fP namespace contains all arcade resources\&. "
.ti -1c
.RI " \fBarcade\fP"
.br
.ti -1c
.RI " \fBarcade::resources\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for arcade from the source code\&.
