on: [ push, pull_request ]
jobs:
  CompileProject:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build project
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev
          sudo apt-get install libsfml-dev
          sudo apt-get install libncurses5-dev libncursesw5-dev
          mkdir build
          cd build/
          cmake ..
          cmake --build . --config Release
          make